### ISSUE TITLE
 'version' key in the manifest file

### ISSUE THREAD

**Issue by mDieli** [nicolasberthel/hass-becker-component#6]
Home Assistant is now requesting (demanding?) an 'version' key in the manifest file.

Error message in the log:

No 'version' key in the manifest file for custom integration 'becker'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'becker'

**Comment by marcschumacher** [comment]
I added PR #9 to fix this.

**Comment by nicolasberthel** [comment]
Fix of @marcschumacher  is merged
